---
kind: pipeline
name: pre-build
resources:
  requests:
    cpu: 400
    memory: 2Gi
steps:
- commands:
  - licensed cache
  - licensed status
  image: public.ecr.aws/kanopy/licensed-go:4.0.4-0.1.0
  name: license-check
  volumes:
  - name: cache
    path: /go
trigger:
  branch:
  - '**/*'
type: kubernetes
volumes:
- name: cache
  path: /go
workspace:
  path: /go/src/github.com/${DRONE_REPO}
---
depends_on:
- pre-build
kind: pipeline
name: amd64
platform:
  arch: amd64
resources:
  requests:
    cpu: 400
    memory: 2Gi
steps:
- commands:
  - make test
  image: golangci/golangci-lint:v1.53.3
  name: test
  pull: always
  volumes:
  - name: cache
    path: /go
- depends_on:
  - test
  environment:
    ARCH: amd64
    GIT_COMMIT: ${DRONE_COMMIT_SHA:0:7}
    PLUGIN_TYPE: drone
  image: plugins/kaniko-ecr
  name: build
  pull: always
  settings:
    build_args:
    - GIT_COMMIT
    - PLUGIN_TYPE
    - ARCH
    create_repository: true
    no_push: true
    repo: ${DRONE_REPO_NAME}
    tags:
    - git-${DRONE_COMMIT_SHA:0:7}-amd64
    - latest-amd64
  volumes:
  - name: cache
    path: /go
  when:
    event:
    - pull_request
- depends_on:
  - test
  environment:
    ARCH: amd64
    GIT_COMMIT: ${DRONE_COMMIT_SHA:0:7}
    PLUGIN_TYPE: drone
  image: plugins/kaniko-ecr
  name: publish
  pull: always
  settings:
    access_key:
      from_secret: ecr_access_key
    build_args:
    - GIT_COMMIT
    - PLUGIN_TYPE
    - ARCH
    create_repository: true
    registry:
      from_secret: ecr_registry
    repo: ${DRONE_REPO_NAME}
    secret_key:
      from_secret: ecr_secret_key
    tags:
    - git-${DRONE_COMMIT_SHA:0:7}-amd64
    - latest-amd64
  volumes:
  - name: cache
    path: /go
  when:
    event:
    - push
- depends_on:
  - test
  environment:
    ARCH: amd64
    GIT_COMMIT: ${DRONE_COMMIT_SHA:0:7}
    PLUGIN_TYPE: drone
    VERSION: ${DRONE_TAG}-amd64
  image: plugins/kaniko-ecr
  name: publish-tag
  pull: always
  settings:
    access_key:
      from_secret: ecr_access_key
    build_args:
    - GIT_COMMIT
    - PLUGIN_TYPE
    - ARCH
    - VERSION
    create_repository: true
    registry:
      from_secret: ecr_registry
    repo: ${DRONE_REPO_NAME}
    secret_key:
      from_secret: ecr_secret_key
    tags:
    - git-${DRONE_COMMIT_SHA:0:7}-amd64
    - ${DRONE_TAG}-amd64
  volumes:
  - name: cache
    path: /go
  when:
    event:
    - tag
trigger:
  branch:
  - '**/*'
type: kubernetes
volumes:
- name: cache
  path: /go
workspace:
  path: /go/src/github.com/${DRONE_REPO}
---
depends_on:
- pre-build
kind: pipeline
name: arm64
platform:
  arch: arm64
resources:
  requests:
    cpu: 400
    memory: 2Gi
steps:
- commands:
  - make test
  image: golangci/golangci-lint:v1.53.3
  name: test
  pull: always
  volumes:
  - name: cache
    path: /go
- depends_on:
  - test
  environment:
    ARCH: arm64
    GIT_COMMIT: ${DRONE_COMMIT_SHA:0:7}
    PLUGIN_TYPE: drone
  image: plugins/kaniko-ecr
  name: build
  pull: always
  settings:
    build_args:
    - GIT_COMMIT
    - PLUGIN_TYPE
    - ARCH
    create_repository: true
    no_push: true
    repo: ${DRONE_REPO_NAME}
    tags:
    - git-${DRONE_COMMIT_SHA:0:7}-arm64
    - latest-arm64
  volumes:
  - name: cache
    path: /go
  when:
    event:
    - pull_request
- depends_on:
  - test
  environment:
    ARCH: arm64
    GIT_COMMIT: ${DRONE_COMMIT_SHA:0:7}
    PLUGIN_TYPE: drone
  image: plugins/kaniko-ecr
  name: publish
  pull: always
  settings:
    access_key:
      from_secret: ecr_access_key
    build_args:
    - GIT_COMMIT
    - PLUGIN_TYPE
    - ARCH
    create_repository: true
    registry:
      from_secret: ecr_registry
    repo: ${DRONE_REPO_NAME}
    secret_key:
      from_secret: ecr_secret_key
    tags:
    - git-${DRONE_COMMIT_SHA:0:7}-arm64
    - latest-arm64
  volumes:
  - name: cache
    path: /go
  when:
    event:
    - push
- depends_on:
  - test
  environment:
    ARCH: arm64
    GIT_COMMIT: ${DRONE_COMMIT_SHA:0:7}
    PLUGIN_TYPE: drone
    VERSION: ${DRONE_TAG}-arm64
  image: plugins/kaniko-ecr
  name: publish-tag
  pull: always
  settings:
    access_key:
      from_secret: ecr_access_key
    build_args:
    - GIT_COMMIT
    - PLUGIN_TYPE
    - ARCH
    - VERSION
    create_repository: true
    registry:
      from_secret: ecr_registry
    repo: ${DRONE_REPO_NAME}
    secret_key:
      from_secret: ecr_secret_key
    tags:
    - git-${DRONE_COMMIT_SHA:0:7}-arm64
    - ${DRONE_TAG}-arm64
  volumes:
  - name: cache
    path: /go
  when:
    event:
    - tag
trigger:
  branch:
  - '**/*'
type: kubernetes
volumes:
- name: cache
  path: /go
workspace:
  path: /go/src/github.com/${DRONE_REPO}
---
depends_on:
- amd64
- arm64
kind: pipeline
name: multi-arch
platform:
  arch: arm64
resources:
  requests:
    cpu: 400
    memory: 2Gi
steps:
- image: public.ecr.aws/kanopy/buildah-plugin:v0.1.0-arm64
  name: manifest-commit
  settings:
    access_key:
      from_secret: ecr_access_key
    manifest:
      sources:
      - git-${DRONE_COMMIT_SHA:0:7}-amd64
      - git-${DRONE_COMMIT_SHA:0:7}-arm64
      targets:
      - git-${DRONE_COMMIT_SHA:0:7}
    registry:
      from_secret: ecr_registry
    repo: ${DRONE_REPO_NAME}
    secret_key:
      from_secret: ecr_secret_key
  volumes:
  - name: cache
    path: /go
  when:
    event:
    - push
- image: public.ecr.aws/kanopy/buildah-plugin:v0.1.0-arm64
  name: manifest-tag
  settings:
    access_key:
      from_secret: ecr_access_key
    manifest:
      sources:
      - ${DRONE_TAG}-amd64
      - ${DRONE_TAG}-arm64
      targets:
      - ${DRONE_TAG}
    registry:
      from_secret: ecr_registry
    repo: ${DRONE_REPO_NAME}
    secret_key:
      from_secret: ecr_secret_key
  volumes:
  - name: cache
    path: /go
  when:
    event:
    - tag
trigger:
  branch:
  - '**/*'
type: kubernetes
volumes:
- name: cache
  path: /go
workspace:
  path: /go/src/github.com/${DRONE_REPO}
